### PR TITLE
Removed catapult publish branch from .drone.yml

### PR DESCRIPTION
**Pull request by burnsed**
For context, see https://clever.atlassian.net/browse/INFRA-1233.

This PR was autogenerated. You were assigned this PR as the most active committer to this repo (or because @xavi- chose you).

Don't be afraid to break protocol and merge this change yourself.  It's pretty low risk.

### CODE REVIEW

**Comment by agclever** [comment]
Closing this because the repo is not being used anymore. @Clever/eng-internal-products should we archive it?

**Comment by burnsed** [comment]
closing...  @nikhilpandit want to archive this repo?

**Comment by nikhilpandit** [comment]
my hesitation against archiving was that it is a public repo, so might have others depending on it. cc @rgarcia - thoughts on archiving unmaintained public repo?

**Comment by rgarcia** [comment]
I think it's fine to archive it w/ a link to new stuff in the description

**Pull request closed without merging**
